### ISSUE TITLE
Build fails on macOS Catalina

### ISSUE THREAD

**Issue by lyons88** [dingusdev/dingusppc#15]
[ 44%] Building CXX object devices/CMakeFiles/devices.dir/adb.cpp.o
In file included from /Users/jam/ding/dingusppc/devices/adb.cpp:28:
In file included from /Users/jam/ding/dingusppc/devices/adb.h:26:
In file included from /Users/jam/ding/dingusppc/thirdparty/SDL2/include/SDL.h:32:
In file included from /Users/jam/ding/dingusppc/thirdparty/SDL2/include/SDL_main.h:25:
/Users/jam/ding/dingusppc/thirdparty/SDL2/include/SDL_stdinc.h:426:5: error: 
      use of undeclared identifier 'memset_pattern4'
    memset_pattern4(dst, &val, dwords * 4);
    ^
1 error generated.
make[3]: *** [devices/CMakeFiles/devices.dir/adb.cpp.o] Error 1
make[2]: *** [devices/CMakeFiles/devices.dir/all] Error 2
make[1]: *** [CMakeFiles/dingusppc.dir/rule] Error 2
make: *** [dingusppc] Error 2

**Comment by maximumspatium** [comment]
It looks like something is wrong with your SDL2 installation.

I tested it on Mac OS 10.13.6 and Macports and got no errors.

Dingusppc doesn't currently use SDL2. The code that used it has been temporarily disabled.

SDL2 dependency will be likely completely removed. There are too many issues with it.

I think it's safe to completely disable SDL2 for now. Give me some time to prepare a patch...

**Comment by lyons88** [comment]
I removed SDL2 installed via brew and installed it via MacPorts, however same error under Catalina...........waits for patch.........

**Comment by maximumspatium** [comment]
@lyons88 Please try out the latest commit in the `master` branch. It works for me.

**Comment by lyons88** [comment]
Still doesn't build on Catalina:

mkdir build && cd build
jamess-Mac-Pro:build jam$ https://github.com/dingusdev/dingusppc.git
-bash: https://github.com/dingusdev/dingusppc.git: No such file or directory
jamess-Mac-Pro:build jam$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:36 (add_subdirectory):
  The source directory

    /Users/jam/dingII/dingusppc/thirdparty/cubeb

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/Users/jam/dingII/dingusppc/build/CMakeFiles/CMakeOutput.log".

**Comment by maximumspatium** [comment]
Dingusppc switched to Git submodules recently. You can fix your build in two ways:

* run `git submodule update --init --recursive` from the root source directory. That works well if you already pulled the latest source code
* using recursive clone with `git clone --recursive`

**Comment by lyons88** [comment]
Still fails with make:

cmake -DCMAKE_BUILD_TYPE=Release ..
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jam/dingII/dingusppc/build
jamess-Mac-Pro:build jam$ make dingusppc
make: *** No rule to make target `dingusppc'.  Stop.
jamess-Mac-Pro:build jam$ make
make: *** No targets specified and no makefile found.  Stop.

**Comment by maximumspatium** [comment]
Looks like your (Apple?) cmake doesn't generate makefiles but assumes Xcode configuration instead.

Try this:

```
cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
make clean
make
```

**Comment by lyons88** [comment]
My mistake, I must have made another build for inside my build dir, and was trying to run make from there.

Builds and run fine now.
