### ISSUE TITLE
Cannot build on Linux Fedora

### ISSUE THREAD

**Issue by maximumspatium** [dingusdev/dingusppc#16]
Building on Linux-Fedora fails with the following error message:

```
[ 89%] Linking CXX executable bin/dingusppc
/usr/bin/ld: thirdparty/loguru/CMakeFiles/loguru.dir/loguru.cpp.o: undefined reference to symbol 'dladdr@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: Fehler: ld gab 1 als Ende-Status zurück
make[2]: *** [CMakeFiles/dingusppc.dir/build.make:153: bin/dingusppc] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:263: CMakeFiles/dingusppc.dir/all] Fehler 2
make: *** [Makefile:150: all] Fehler 2
```
Steps to reproduce:
```
cd [dingusppc root directory]
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
```
OS: Fedora 32 (Workstation Edition)
Compiler: gcc (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)
cmake version 3.17.2

**Comment by Waqar144** [comment]
> ```
> cd [dingusppc root directory]
> mkdir build && cd build
> cmake -DCMAKE_BUILD_TYPE=Release ..
> make
> 
> ```

You need `-DBUILD_SHARED_LIBS=ON`in addition to that to reproduce this.

**Comment by maximumspatium** [comment]
@Waqar144 It works without `-DBUILD_SHARED_LIBS=ON` on both Mac and Linux. Thanks a lot!

I think the issue can be closed.
