### ISSUE TITLE
CMake Error at CMakeLists.txt:96 (install) SOLVED

### ISSUE THREAD

**Issue by webspacecreations** [dingusdev/dingusppc#18]
Upon trying to compile on Raspbian/ARM (cmake may be a few iterations behind), the following final error is given:
CMake Error at CMakeLists.txt:96 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "dingusppc".

**Open CMakeLists.txt and change the line to:**
install (TARGETS dingusppc DESTINATION ${PROJECT_SOURCE_DIR}/build)

This resolves the build problem and drops the binary into the build directory. As an aside, the following additional modules were needed for successful compilation:
_sudo apt install doxygen graphviz_

**Comment by dingusdev** [comment]
Fixed the line and also noted the issue in readme.md
