### ISSUE TITLE
Support emulated battery, ac adapter

### ISSUE THREAD

**Issue by upintheairsheep** [dingusdev/dingusppc#53]
Can you add an optional virtual battery, as a virtual battery is required for the battery desk accessory and battery indicators in Mac OS X? 

For reference, see https://www.mail-archive.com/qemu-devel@nongnu.org/msg776834.html .

**Comment by maximumspatium** [comment]
Thanks for your suggestion. We will eventually introduce some virtual power management to dingusppc as soon as it's capable of emulating a portable machine compatible with Mac OS X.
For now, dingusppc supports desktop machines only.

**Comment by upintheairsheep** [comment]
Closed to be implemented when said portable machine support is added, along with other portable-specific hardware such as lid closing and the PowerBook control panels in Classic Mac OS.
