### ISSUE TITLE
Testing DingusPPC on openSUSE 

### ISSUE THREAD

**Issue by Lucas-mother3** [dingusdev/dingusppc#63]
I was looking into compiling DingusPPC on openSUSE Tumbleweed, and find out that the default process for making tests didn't work as stated because `testppc` is not available on the Makefile.

**Comment by dingusdev** [comment]
Did you enable the DPPC_BUILD_PPC_TESTS build flag?

**Comment by Lucas-mother3** [comment]
> Did you enable the DPPC_BUILD_PPC_TESTS build flag?

Ah... Alright, I didn't notice that one. I could ask to update the section in "testing PPC emulation".

**Comment by dingusdev** [comment]
Got it updated.

**Comment by Lucas-mother3** [comment]
Closing issue now
