### ISSUE TITLE
[BUG] Compile issues in openSUSE

### ISSUE THREAD

**Issue by Lucas-mother3** [dingusdev/dingusppc#65]
**Describe the bug**
DingusPPC release builds failed to build under openSUSE Tumbleweed.

**To Reproduce**
1. Follow build instructions on README.md under openSUSE
2. Wait a while
3. Compilation should return an error

**Expected behavior**
I expected to have a build of DingusPPC to test whenever it is viable to run Mac OS on it.

**Screenshots**
![image](https://github.com/dingusdev/dingusppc/assets/76678069/48081854-3210-4aeb-8c9c-d363b7e7c6a7)

**Device Information (please complete the following information):**

 - Device Type: Desktop
 - Host OS: openSUSE Tumbleweed 20231117 (kernel 6.6.1-1-default)
 - Host Processor: Intel Core i3-3340 @ 3.3GHz
 - Host RAM: 8 GB
 - Build Date: 24/11/2023

**Additional context**
Context should be seen in the following screenshot. The screenshot provides the error information much clearly.

**Comment by dingusdev** [comment]
Try replacing `find` in those instances with `std:find`.

**Comment by rndtrash** [comment]
It looks like adding `#include <algorithm>` to the `machineproperties.cpp` file solves this issue.

---

By the way,

```cpp
using namespace std;
```

why?

**Comment by dingusdev** [comment]
Got the fix in. As for those std namespace statements, I could remove most of it and specify it. Though to be fair, it's not as if CubeB didn't do this it.

**Comment by Lucas-mother3** [comment]
Closing this issue as I successfully compiled a binary.
