### ISSUE TITLE
[BUG] SDL2Config.cmake and sdl2-config.cmake not found by SDL2 during compiling on Linux

### ISSUE THREAD

**Issue by pootispenserhere4723** [dingusdev/dingusppc#82]
**Describe the bug**
```
CMake Error at CMakeLists.txt:14 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

**To Reproduce**
1. Clone DingusPPC
2. Follow the instructions
3. Execute "cmake -DCMAKE_BUILD_TYPE=Release .."

**Expected behavior**
The emulator compiles with no issues

**Screenshots**
**Device Information (please complete the following information):**

 - Device Type: Desktop
 - Host OS: Linux Mint 21.3 Cinnamon
 - Host Processor: AMD Athlon 5158
 - Host RAM: 8GB
 - Guest OS: Attempting to emulate Mac OS 9.2
 - Guest Processor: [e.g. PowerPC G3 (750 v.1)]
 - Guest ROM: [e.g. Power Mac G3 Beige]
 - Guest RAM: [e.g. 64 MB]
 - Build Date: [e.g. 22/7/2019 (dd/mm/yyyy format)]
 - Version: Latest

**Comment by dingusdev** [comment]
Run `$ sudo apt install libsdl2-dev`

**Comment by Orion107** [comment]
This is also happening on Windows, how do I fix?

**Comment by dingusdev** [comment]
[Try this.](https://github.com/GlowCheese/SDL2-Setup)
