### ISSUE TITLE
[BUG]  Compile issues in termux

### ISSUE THREAD

**Issue by spz2020** [dingusdev/dingusppc#97]
**Describe the bug**
DingusPPC git builds failed to build under termux

**To Reproduce**

1. Follow build instructions on README.md under termux
2. Wait a while
3. Compilation should return an error

**Expected behavior**
can build

**Screenshots**
![Screenshot_2024-06-30-11-54-15-75_84d3000e3f4017145260f7618db1d683](https://github.com/dingusdev/dingusppc/assets/74664513/0e3f753b-f790-4bcf-b6a7-49a0662f3ae4)

**Device Information (please complete the following information):**

 - Device Type: Smartphone
 - Host OS: Linux localhost 4.14.186+
 - Host Processor: Skipped because of a compilation error
 - Host RAM: Skipped because of a compilation error
 - Guest OS: Skipped because of a compilation error
 - Guest Processor: Skipped because of a compilation error
 - Guest ROM: Skipped because of a compilation error
 - Guest RAM: Skipped because of a compilation error
 - Build Date 30/6/2024
 - Version https://github.com/dingusdev/dingusppc/commit/5eaff7a8ceec374c545328a458fbfd5620a12bef

**Additional context**
```
ld.lld: error: duplicate symbol: now_ns()
>>> defined at ppcexec.cpp
>>>            cpu/ppc/CMakeFiles/cpu_ppc.dir/ppcexec.cpp.o:(now_ns())
>>> defined at cubeb_aaudio.cpp
>>>            cubeb_aaudio.cpp.o:(.text+0x0) in archive lib/libcubeb.a
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by joevt** [comment]
Added a commit to my fork to fix this:
 https://github.com/joevt/dingusppc/commit/18bde6eab4f1acfe61cbe7af09b00f7e04037d8c

**Comment by dingusdev** [comment]
Changed now_ns in loguru and ppc_exec with dingusdev/dingusppc@17cdcc5560961c7d85df5a536826206c9c436b51
